turtle = {}

function turtle.forward() end
function turtle.back() end
function turtle.up() end
function turtle.down() end
function turtle.turnLeft() end
function turtle.turnRight() end
function turtle.dig(side) end
function turtle.digUp(side) end
function turtle.digDown(side) end
function turtle.place(text) end
function turtle.placeUp(text) end
function turtle.placeDown(text) end
function turtle.drop(count) end
function turtle.dropUp(count) end
function turtle.dropDown(count) end
function turtle.select(slot) end
function turtle.getItemCount(slot) end
function turtle.getItemSpace(slot) end
function turtle.detectUp() end
function turtle.detectDown() end
function turtle.compare() end
function turtle.compareUp() end
function turtle.compareDown() end
function turtle.attackside() end
function turtle.attackUpside() end
function turtle.attackDownside() end
function turtle.suck(count) end
function turtle.suckUp(count) end
function turtle.suckDown(count) end
function turtle.getFuelLevel() end
function turtle.equipLeft() end
function turtle.equipRight() end
function turtle.inspect() end
function turtle.inspectUp() end
function turtle.inspectDown() end
function turtle.getItemDetails(slot) end
function turtle.craft(limit) end

return turtle